### ISSUE TITLE
Zapełnianie bazy skryptem

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-main#5]
Taki bug mi leci podczas zapełniana bazy
![Screenshot from 2021-11-20 10-54-40](https://user-images.githubusercontent.com/70373402/142722109-c9dbb275-3035-4967-8e86-e16a2d9be9c4.png)

**Comment by wnekus** [comment]
Każde dodanie usera powoduje ten bug, także to nie problem ze skryptem

**Comment by sswrk** [comment]
Problem był z image service
